### ISSUE TITLE
Pointer to local variable

### ISSUE THREAD

**Issue by septillion-git** [msh2050/TimeCounter#1]
```C++
char * timecounter::getsHHMMSS()
{
	
	uint8_t j;
	char buffer[10];
	j = 0;
	j = sprintf(buffer, "%02d:", numberOfHours(counter));
	j += sprintf(buffer + j, "%02d:", numberOfMinutes(counter));
	j += sprintf(buffer + j, "%02d", numberOfSeconds(counter));
	return buffer;
}
```
You return a pointer to a local variable. At the end of the function buffer goes out of scope. Therefor you have no guarantee the content the pointer is pointing to is still valid data.

**Comment by msh2050** [comment]
can you suggest/hint any correction please.

**Comment by septillion-git** [comment]
Easy option, make buffer a variable in the class. That will stay alive.

But an even nicer way in my eyes is to not put it in a buffer. Let the Print-class do all the heavy lifting. Most libraries involving printing strings (and all if you count proper libraries) implement the Print class. So the function can look like
```C++
size_t TimeFormater::printHHMMSS(Print& out){
  size_t size = 0;
  
  size += out.print(getHours(time)); 
  size += out.write(':');
  size += out.print(getMinutes(time)); 
  size += out.write(':'); 
  size += out.print(setSeconds(time));
  
  return size;
}
```

Or, if you make the object of print a class variable as well (which you can assign at the beginning so you can have multiple instances which print to different outputs
```C++
size_t TimeFormater::printHHMMSS(){
  size_t size = 0;
  // Assuming _out to be a class pointer to a Print class (supporting object)

  size += _out->print(getHours(time)); 
  size += _out->write(':');
  size += _out->print(getMinutes(time)); 
  size += _out->write(':'); 
  size += _out->print(setSeconds(time));
  
  return size; //number of chars written
}
```

AndI would also streamline the calculation of H, M and S a bit. It does a lot of calculations double at the moment.

**Comment by msh2050** [comment]
Dear @septillion-git 
thanks a lot, 
your samples force me to study C++ more and change the way I'm thinking...
I think that your second example is the way I should go with.

with best regards

**Comment by septillion-git** [comment]
Glad I could be of any help :)

**Comment by msh2050** [comment]
https://github.com/msh2050/TimeFormater/commit/7a32451e9efadc0eb11832d17e5a6f20291a0ecf?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8
